### ISSUE TITLE
Invalid direction vector after constraints

### ISSUE THREAD

**Issue by jmccrae** [ybyygu/rust-lbfgs#13]
This version is failing as follows:

https://gist.github.com/jmccrae/6dd2c64c9cbbe2432efe7e7b2cd525a2

```
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `0.0`,
 right: `0.0`: invalid direction vector after constraints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]', /home/jmccrae/.cargo/git/checkouts/rust-lbfgs-5379d93d310fea43/839d015/src/lbfgs.rs:600:9
```

(NB: This test also would fail Issue 12 before the fix)

**Comment by ybyygu** [comment]
Thank you for your report! It could be a bug in OWL-QN algorithm introduced during refacotrization. I need some time to dive into the details.

**Comment by ybyygu** [comment]
After careful evaluation, I confirmed my implementation is in par with libbfgs implemented in C. I tested your code with original [libbfgs](https://github.com/chokkan/liblbfgs), which also failed for similar reason. Indeed, there is some case, OWL-QN algorithm does not converge. See this [paper](http://proceedings.mlr.press/v37/gonga15.pdf) for details. Please also check your gradient calculation in your codes to make sure its correctness.

**Comment by ybyygu** [comment]
The codes related to OWL-QN algorithm has been improved. The correctness was validated against the example ported from [R lbfgs](https://cran.r-project.org/web/packages/lbfgs/) package. Now the codes will return an error instead of hard failure (assert panic) if applicable.

However, these commits do not resolve your issue. I guess it is related to the limitation of OWL-QN algorithm or your gradient implementation in your test.
